package server

import (
	"fmt"

	"github.com/gin-gonic/gin"
	v1 "github.com/yobol/yobol/api/v1"
	"github.com/yobol/yobol/config"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "github.com/yobol/yobol/docs" // generated by SWAG CLI
)

type server interface {
	ListenAndServe() error
}

func Run() {
	// gin.Default() will return a *gin.Engine with the Logger and Recovery middlewares already attached.
	// gin.New() will return a *gin.Engine without any middleware attached.
	router := gin.Default()
	if err := v1.MountApiGroups(router); err != nil {
		panic(err)
	}
	// use ginSwagger middleware to serve the API docs
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	address := fmt.Sprintf(":%d", config.C.Server.Port)
	fmt.Printf("server run on: %s\n", address)
	s := initServer(address, router)
	if err := s.ListenAndServe(); err != nil {
		panic(err)
	}
}
