<<<<<<< HEAD
basePath: /api/v1
=======
basePath: /apidocs/#/
>>>>>>> 5b00e475eb6f9bee36e65938240180b4048bf3fc
host: host:8080
info:
  contact:
    email: yobol1024@gmail.com
    name: Yobol
    url: yobol.me (unavailble)
  title: API Docs for Yobol
  version: 1.0.0
paths: {}
schemes:
- http
- https
swagger: "2.0"
