package main

import (

	// swagger embed files
	// gin-swagger middleware
	"github.com/yobol/yobol/config"
	"github.com/yobol/yobol/core/server"
	_ "github.com/yobol/yobol/docs" // generated by SWAG CLI
)

const (
	AuthCookieName = "YAC"
)

// General API Info
// Format Reference: https://github.com/swaggo/swag/blob/master/README.md#declarative-comments-format

// @title       API Docs for Yobol
// @version     1.0.0
// @descrption  API Docs for Yobol

// @contact.name   Yobol
// @contact.email  yobol1024@gmail.com
// @contact.url    yobol.me (unavailble)

// @Schemes   https http
// @host      host:8080
// @BasePath  /

func main() {
	config.Init()

	server.Run()
}
