package v1

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/yobol/yobol/api/v1/auth"
	"github.com/yobol/yobol/api/v1/user"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "github.com/yobol/yobol/docs" // generated by SWAG CLI
)

type Groups struct {
	auth.AuthGroup
	user.UserGroup
}

var ApiGroups = new(Groups)

func MountApiGroups() http.Handler {
	router := gin.Default()

	// use ginSwagger middleware to serve the API docs
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	return router
}
